<?php

declare(strict_types=1);
$root=getcwd(); if(!is_file($root.'/includes/framework.php')){fwrite(STDERR,"Run from Joomla root.\n");exit(1);} $_SERVER['HTTP_HOST']='localhost';
define('_JEXEC',1);define('JPATH_BASE',$root);require JPATH_BASE.'/includes/defines.php';require JPATH_BASE.'/includes/framework.php';define('JPATH_COMPONENT',JPATH_ADMINISTRATOR.'/components/com_xdecaropeople');define('JPATH_COMPONENT_ADMINISTRATOR',JPATH_COMPONENT);
$c=\Joomla\CMS\Factory::getContainer();$c->alias('session','session.cli')->alias('JSession','session.cli')->alias(\Joomla\CMS\Session\Session::class,'session.cli')->alias(\Joomla\Session\Session::class,'session.cli')->alias(\Joomla\Session\SessionInterface::class,'session.cli');$app=$c->get('JApplicationAdministrator');\Joomla\CMS\Factory::$application=$app;$app->createExtensionNamespaceMap();$db=$c->get(\Joomla\Database\DatabaseInterface::class);$q=$db->getQuery(true)->select('id')->from('#__users')->where($db->quoteName('username').'='.$db->quote('admin'));$admin=(int)$db->setQuery($q,0,1)->loadResult();$app->loadIdentity($c->get(\Joomla\CMS\User\UserFactoryInterface::class)->loadUserById($admin));
$component=$app->bootComponent('com_xdecaropeople');$backup=$component->getBackupService();$restore=$component->getRestoreService();

$canonicalCurrent=static function()use($db):string{$tables=[];foreach(\xdecaro\Component\People\Administrator\Service\BackupService::BACKUP_TABLES as $table){$q=$db->getQuery(true)->select('*')->from($db->quoteName($table))->order($db->quoteName('id').' ASC');$rows=array_values((array)$db->setQuery($q)->loadAssocList());foreach($rows as &$row)ksort($row,SORT_STRING);unset($row);$tables[$table]=$rows;}return \xdecaro\Component\People\Administrator\Service\BackupService::canonicalJson(['tables'=>$tables]);};
$zipData=static function(string $path):array{$z=new \ZipArchive();$z->open($path);$d=['manifest'=>$z->getFromName('manifest.json'),'data'=>$z->getFromName('data.json')];$z->close();return $d;};
$baseline=$backup->create($admin,'full_restore_fixture');$baselineZip=$zipData((string)$baseline['path']);$baselineData=(string)$baselineZip['data'];
$q=$db->getQuery(true)->select('COUNT(*)')->from('#__users');$usersBefore=(int)$db->setQuery($q)->loadResult();$backupsBefore=count($backup->list());$q=$db->getQuery(true)->select('COUNT(*)')->from('#__xdecaropeople_maintenance_log');$logsBefore=(int)$db->setQuery($q)->loadResult();
$extra=(object)['uuid'=>'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','display_name'=>'Restore Extra','first_name'=>'Restore','last_name'=>'Extra','person_status'=>'active','state'=>1,'access'=>1,'created'=>\Joomla\CMS\Factory::getDate()->toSql(),'created_by'=>$admin];$db->insertObject('#__xdecaropeople_people',$extra,'id');
$result=$restore->restoreFull((string)$baseline['path'],$admin);
if(empty($result['safety_backup_uuid'])||($result['integrity_ok']??false)!==true){fwrite(STDERR,"Full restore result incomplete.\n");exit(1);}if($canonicalCurrent()!==$baselineData){fwrite(STDERR,"Full restore did not reproduce backup dataset exactly.\n");exit(1);}if(count($backup->list())<$backupsBefore+1){fwrite(STDERR,"Pre-restore safety backup was not preserved.\n");exit(1);}$q=$db->getQuery(true)->select('COUNT(*)')->from('#__xdecaropeople_maintenance_log');if((int)$db->setQuery($q)->loadResult()<$logsBefore){fwrite(STDERR,"Maintenance log was overwritten by restore.\n");exit(1);}$q=$db->getQuery(true)->select('COUNT(*)')->from('#__users');if((int)$db->setQuery($q)->loadResult()!==$usersBefore){fwrite(STDERR,"External Joomla data changed during restore.\n");exit(1);}

$beforeFailure=$canonicalCurrent();$backupCountBeforeFailure=count($backup->list());$entries=$zipData((string)$baseline['path']);$data=json_decode((string)$entries['data'],true,512,JSON_THROW_ON_ERROR);if(empty($data['tables']['#__xdecaropeople_people'])){fwrite(STDERR,"Need a person row for rollback fixture.\n");exit(1);}unset($data['tables']['#__xdecaropeople_people'][0]['first_name']);$dataJson=\xdecaro\Component\People\Administrator\Service\BackupService::canonicalJson($data);$manifest=json_decode((string)$entries['manifest'],true,512,JSON_THROW_ON_ERROR);$manifest['payload_sha256']=hash('sha256',$dataJson);$manifestJson=\xdecaro\Component\People\Administrator\Service\BackupService::canonicalJson($manifest);$bad='/tmp/people-restore-rollback.zip';$z=new \ZipArchive();$z->open($bad,\ZipArchive::CREATE|\ZipArchive::OVERWRITE);$z->addFromString('manifest.json',$manifestJson);$z->addFromString('data.json',$dataJson);$z->addFromString('SHA256SUMS.txt',hash('sha256',$dataJson)."  data.json\n".hash('sha256',$manifestJson)."  manifest.json\n");$z->close();
$thrown=false;try{$restore->restoreFull($bad,$admin);}catch(\Throwable){$thrown=true;}if(!$thrown){fwrite(STDERR,"Malformed full restore did not fail.\n");exit(1);}if($canonicalCurrent()!==$beforeFailure){fwrite(STDERR,"Rollback did not preserve pre-failure People data.\n");exit(1);}if(count($backup->list())<$backupCountBeforeFailure+1){fwrite(STDERR,"Safety backup did not survive failed restore.\n");exit(1);}
$q=$db->getQuery(true)->select('COUNT(*)')->from('#__xdecaropeople_maintenance_log')->where($db->quoteName('action').'='.$db->quote('backup_create'))->where($db->quoteName('metadata').' LIKE '.$db->quote('%pre_restore%'));if((int)$db->setQuery($q)->loadResult()<2){fwrite(STDERR,"Safety backups are not marked pre_restore.\n");exit(1);}
echo "People 1.7.28 full restore runtime OK\n";
