CREATE TABLE IF NOT EXISTS `#__xdecaropeople_people` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `user_id` INT UNSIGNED DEFAULT NULL,
  `display_name` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(150) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `preferred_name` VARCHAR(150) DEFAULT NULL,
  `birth_date` DATE DEFAULT NULL,
  `sex` CHAR(1) DEFAULT NULL,
  `disability_status` TINYINT DEFAULT NULL,
  `disability_types` LONGTEXT DEFAULT NULL,
  `disability_other` VARCHAR(190) DEFAULT NULL,
  `accessibility_needs` LONGTEXT DEFAULT NULL,
  `accessibility_other` VARCHAR(190) DEFAULT NULL,
  `nationality_code` CHAR(3) DEFAULT NULL,
  `nationality_codes` LONGTEXT DEFAULT NULL,
  `birth_country_code` CHAR(2) DEFAULT NULL,
  `birth_place` VARCHAR(190) DEFAULT NULL,
  `birth_place_id` VARCHAR(64) DEFAULT NULL,
  `birth_region` VARCHAR(190) DEFAULT NULL,
  `tax_identifier` VARCHAR(64) DEFAULT NULL,
  `email` VARCHAR(254) DEFAULT NULL,
  `phone` VARCHAR(50) DEFAULT NULL,
  `whatsapp` VARCHAR(50) DEFAULT NULL,
  `preferred_contact` VARCHAR(32) DEFAULT NULL,
  `address_line` VARCHAR(255) DEFAULT NULL,
  `address_number` VARCHAR(32) DEFAULT NULL,
  `postal_code` VARCHAR(32) DEFAULT NULL,
  `city` VARCHAR(190) DEFAULT NULL,
  `region` VARCHAR(190) DEFAULT NULL,
  `country_code` CHAR(2) DEFAULT NULL,
  `residence_place_id` VARCHAR(64) DEFAULT NULL,
  `additional_addresses` LONGTEXT DEFAULT NULL,
  `relations_data` LONGTEXT DEFAULT NULL,
  `language` VARCHAR(16) DEFAULT NULL,
  `social_instagram` VARCHAR(255) DEFAULT NULL,
  `social_facebook` VARCHAR(255) DEFAULT NULL,
  `social_linkedin` VARCHAR(255) DEFAULT NULL,
  `social_tiktok` VARCHAR(255) DEFAULT NULL,
  `social_telegram` VARCHAR(255) DEFAULT NULL,
  `social_x` VARCHAR(255) DEFAULT NULL,
  `social_youtube` VARCHAR(255) DEFAULT NULL,
  `website_url` VARCHAR(255) DEFAULT NULL,
  `profile_document_uuid` CHAR(36) DEFAULT NULL,
  `person_status` VARCHAR(16) NOT NULL DEFAULT 'active',
  `source_component` VARCHAR(64) DEFAULT NULL,
  `notes` TEXT DEFAULT NULL,
  `state` TINYINT NOT NULL DEFAULT 1,
  `access` INT UNSIGNED NOT NULL DEFAULT 1,
  `created` DATETIME NOT NULL,
  `created_by` INT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME DEFAULT NULL,
  `modified_by` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_people_uuid` (`uuid`),
  UNIQUE KEY `idx_people_user_id` (`user_id`),
  KEY `idx_people_name` (`last_name`,`first_name`),
  KEY `idx_people_email` (`email`),
  KEY `idx_people_tax_identifier` (`tax_identifier`),
  KEY `idx_people_birth` (`birth_date`),
  KEY `idx_people_person_status` (`person_status`),
  KEY `idx_people_state_access` (`state`,`access`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__xdecaropeople_history` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_id` INT UNSIGNED NOT NULL,
  `action` VARCHAR(32) NOT NULL,
  `changed_fields` TEXT DEFAULT NULL,
  `actor_user_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_people_history_person` (`person_id`,`created`),
  KEY `idx_people_history_actor` (`actor_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
